apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pulso
  labels:
    app: pulso
spec:
  selector:
    matchLabels:
      app: pulso
  template:
    metadata:
      labels:
        app: pulso
    spec:
      containers:
        - name: pulso
          image: pulso:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              name: metrics

          volumeMounts:
            - name: storage
              mountPath: /data

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pulso-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulso-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi