apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pulso
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: pulso

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s